CREATE TABLE employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           department VARCHAR(255) NOT NULL,
                           role VARCHAR(255) NOT NULL,
                           joining_date DATE NOT NULL
);

CREATE TABLE review_cycles (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL,
                               start_date DATE NOT NULL,
                               end_date DATE NOT NULL,
                               CONSTRAINT chk_cycle_dates CHECK (end_date >= start_date)
);

CREATE TABLE performance_reviews (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     employee_id BIGINT NOT NULL,
                                     review_cycle_id BIGINT NOT NULL,
                                     rating INT NOT NULL,
                                     reviewer_notes TEXT,
                                     submitted_at TIMESTAMP NOT NULL,
                                     CONSTRAINT fk_pr_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
                                     CONSTRAINT fk_pr_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles(id),
                                     CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE goals (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       employee_id BIGINT NOT NULL,
                       review_cycle_id BIGINT NOT NULL,
                       title VARCHAR(255) NOT NULL,
                       status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'MISSED')),
                       CONSTRAINT fk_goal_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
                       CONSTRAINT fk_goal_cycle FOREIGN KEY (review_cycle_id) REFERENCES review_cycles(id)
);

-- Indexes for common lookups
CREATE INDEX idx_employee_dept ON employees(department);
CREATE INDEX idx_pr_employee ON performance_reviews(employee_id);
CREATE INDEX idx_pr_cycle ON performance_reviews(review_cycle_id);
CREATE INDEX idx_goal_employee ON goals(employee_id);
CREATE INDEX idx_goal_cycle ON goals(review_cycle_id);